copy ARIALBD.TTF    c:\windows\fonts
copy ARIALBI.TTF    c:\windows\fonts
copy COMIC.TTF      c:\windows\fonts
copy COMICBD.TTF    c:\windows\fonts
copy COUR.TTF       c:\windows\fonts
copy COURBD.TTF     c:\windows\fonts
copy COURBI.TTF     c:\windows\fonts
copy COURI.TTF      c:\windows\fonts
copy CURSIVE.TTF    c:\windows\fonts
copy RANS____.TTF   c:\windows\fonts
copy STENCIL.TTF    c:\windows\fonts
copy TIMES.TTF      c:\windows\fonts
copy TIMESBD.TTF    c:\windows\fonts
copy TIMESBI.TTF    c:\windows\fonts
copy TIMESI.TTF     c:\windows\fonts
copy VERDANA.TTF    c:\windows\fonts
copy VERDANAB.TTF   c:\windows\fonts
copy ARIAL.TTF      c:\windows\fonts
copy VERDANAI.TTF   c:\windows\fonts
copy VERDANAZ.TTF   c:\windows\fonts
copy BRITANIC.TTF   c:\windows\fonts
